name: monorepo
publish_to: 'none'

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: '3.32.1'

dependencies:
    auto_route: ^10.1.0+1
    cupertino_icons: ^1.0.8
    data_flutter_secure_storage:
        path: data/flutter_secure_storage
    data_json_serializable:
        path: data/json_serializable
    data_maya_services:
        path: data/maya_services
    design_system:
        path: design_system
    dio: ^5.8.0+1
    domain:
        path: domain
    flutter:
        sdk: flutter
    flutter_bloc: ^9.1.1
    flutter_localizations:
        sdk: flutter
    freezed: ^3.0.6
    freezed_annotation: ^3.0.0
    intl: ^0.20.2
    logging: ^1.3.0
    provider: ^6.1.5

dev_dependencies:
    auto_route_generator: ^10.2.3
    build_runner: ^2.4.15
    flutter_lints: ^5.0.0
    flutter_test:
        sdk: flutter

workspace:
  - data/flutter_secure_storage
  - data/json_serializable
  - data/maya_services
  - domain
  - design_system